### ISSUE TITLE
Make help menu interactions exclusive to the command author

### ISSUE THREAD

**Issue by sagamantus** [GDSC-IIIT-Kalyani/hacktobot#11]
# Make help menu interactions exclusive to the command author
Currently, everyone can control the help menu using the buttons. We need to make sure that only the command author should be able to interact with the buttons to change the pages of the help menu.
Make necessary changes in `utils/helper.py`.

Make sure to read and follow [Contributing Guidelines](https://github.com/GDSC-IIIT-Kalyani/hacktobot/blob/main/CONTRIBUTING.md).

**Comment by ppap1771** [comment]
Please assign this issue to me @sagamantus, I would love to work on it.

**Comment by sagamantus** [comment]
@ppap1771 There you go! If you encounter any issues, feel free to ping me.
