### ISSUE TITLE
GitHub Issue Template

### ISSUE THREAD

**Issue by sagamantus** [GDSC-IIIT-Kalyani/hacktobot#2]
# GitHub Issue Template
Add templates for new issues.

- [ ] Bug reports
- [ ] Feature requests

Must be created in `.github/ISSUE_TEMPLATES`, and named `bug-report.md` and `feature.md` respectively.

Reference:
- [GitHub's Documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- [GitHub Issue Templates](https://github.com/stevemao/github-issue-templates)

Don't forget to read the[Contributing Guidelines](https://github.com/GDSC-IIIT-Kalyani/hacktobot/blob/main/CONTRIBUTING.md).

**Comment by JurassikLizard** [comment]
Could this be assigned to me?

**Comment by sagamantus** [comment]
Yeah, it slipped out of my mind. Sorry about that.

**Comment by g33tansh** [comment]
Can I please be assigned to this issue?
