### ISSUE TITLE
GitHub Pull Request Template

### ISSUE THREAD

**Issue by sagamantus** [GDSC-IIIT-Kalyani/hacktobot#4]
# GitHub Pull Request Template

Add templates for new pull requests.

It should contain a checklist of fundamental things required in the PR (such as did you read the [Contributing Guidelines](https://github.com/GDSC-IIIT-Kalyani/hacktobot#contributing-to-hacktobot)), and sections to explain various elements related to the PR.

Must be created in `.github/PULL_REQUEST_TEMPLATE `, and named `pull_request_template.md`.

Reference:
- [GitHub's Documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [GitHub PR Template Examples](https://github.com/stevemao/github-issue-templates)

Don't forget to read the [Contributing Guidelines](https://github.com/GDSC-IIIT-Kalyani/hacktobot/blob/main/CONTRIBUTING.md).

**Comment by alvinokafor** [comment]
@sagamantus, I would love to work on this

**Comment by sagamantus** [comment]
@alvinokafor sure. I'll assign you this issue.

**Comment by g33tansh** [comment]
Can I work on this issue?

**Comment by sagamantus** [comment]
@g33tansh yeah sure.
