### ISSUE TITLE
Feature: `.npm` command

### ISSUE THREAD

**Issue by Ayushi8989** [GDSC-IIIT-Kalyani/hacktobot#6]
# Feature: `.npm` command
A `.npm` command can be useful to provide information about a specific package from npm.

## Usage
```
.npm <package_name>
```
Example usage:
```
.npm react
```
## Additional Details
We can use the [registry npmjs](https://registry.npmjs.org/) for this.
I would like to implement this command.

**Comment by sagamantus** [comment]
@Ayushi8989 alright, I'll assign you this issue.

Please keep your file in the `./exts/utilities` directory.
